#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

xrandr --auto
xrandr --output HDMI-1 --auto --right-of eDP-1
feh --bg-fill ~/.backgrounds/himalaya-night.jpg ~/.backgrounds/himalaya-night.jpg
xsetroot -cursor_name left_ptr
unclutter -grab &
compton &
exec xmonad

