#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

export PATH="$HOME/bin:$HOME/.local/bin:$HOME/.cargo/bin:$HOME/.cabal/bin:$PATH"
export VISUAL=nvim
export EDITOR=nvim
export TERMINAL=alacritty
export _JAVA_AWT_WM_NONREPARENTING=1

if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
  exec startx -- -keeptty &> /dev/null
fi

